name: "[Csv2ImgCmd] Build and Test Sources"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test_cmd:
    name: "Build Csv2ImgCmd"
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ env.LOCAL != 'true' }}
        with:
          xcode-version: latest-stable
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Build and Test
        run: |
          set -o pipefail && \
          xcodebuild -scheme Csv2ImgCmd \
          clean build \
          -destination 'platform=OS X,arch=arm64' \
          | xcbeautify
