name: "[Csv2ImgCore] Build and Test Sources"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test_core:
    name: "Build Csv2ImgCore"
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ env.LOCAL != 'true' }}
        with:
          xcode-version: latest-stable
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Build and Test (osX)
        run: |
          set -o pipefail && \
          xcodebuild -scheme Csv2ImgCore \
          clean build test \
          -destination 'platform=OS X,arch=arm64' \
          | xcbeautify
      - name: Build and Test (iOS)
        run: |
          set -o pipefail && \
          xcodebuild -scheme Csv2ImgCore \
          clean build test \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          | xcbeautify
