name: "[Csv2Img] Build and Test Sources"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: "Build Csv2Img"
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install xcpretty
        run: bundle install
      - name: Build and Test
        run: |
          set -o pipefail && \
          xcodebuild -scheme Csv2Img \
          clean build test \
          -destination 'platform=OS X,arch=arm64' \
          -destination 'platform=iOS Simulator,name=iPhone 13' \
          | bundle exec xcpretty
